const { ovlcmd } = require('../lib/ovlcmd');
const store = require('../lib/onepiece_store');

const MENU = `🏴‍☠️ *ONE PIECE WORLD TOUR — OVL*

📌 *Départ et profil*
.opchoisir | .opprofil | .opmenu | .opguide

🗺️ *Aventure*
.opchapitre | .opquete | .opmission | .opdaily
.opcombat | .opboss | .opcolisee | .opprime

⚔️ *Puissance*
.ophaki | .optrain | .oparme | .opfruit
.opinventaire | .opshop | .opacheter | .oplootbox

🚢 *Équipage et mer*
.opbateau | .opexpedition | .opequipage | .opfleet
.oppeche | .opdenden

🏆 *Groupe et classements*
.opclassement | .opstats | .opreset

Réponds à .opguide pour voir les règles et les sous-commandes.`;

function text(arg) { return Array.isArray(arg) ? arg.join(' ').trim() : String(arg || '').trim(); }
function lower(arg) { return text(arg).toLowerCase(); }
function userLabel(id) { return `@${String(id || '').split('@')[0]}`; }
function isGroup(jid) { return String(jid || '').endsWith('@g.us'); }
function target(arg, self) { const match = text(arg).match(/@?(\d{5,20})(?:@\w+)?/); return match ? `${match[1]}@s.whatsapp.net` : self; }
function findUser(jid, id) { return store.getUser(jid, id); }
async function reply(repondre, message) { return repondre(message); }
async function mentionReply(sock, jid, message, mentions, repondre) {
  if (sock && typeof sock.sendMessage === 'function' && mentions?.length) return sock.sendMessage(jid, { text: message, mentions });
  return reply(repondre, message);
}
function saveUser(user, author) { if (author) user.name = String(author).split('@')[0]; return store.update(user); }
function requireProfile(user, repondre) { if (!user.race || !user.className) { repondre('⚠️ Crée ton profil avec *.opchoisir humain pirate* avant de jouer.'); return false; } return true; }
function gain(user, amount) { return store.addXp(user, amount); }
function progress(user) { return `${user.xp}/${store.xpFor(user.level)} XP`; }
function bar(value, max = 100) { const filled = Math.round((Math.max(0, value) / max) * 10); return '█'.repeat(filled) + '░'.repeat(10 - filled); }
function profile(user) { return `🏴‍☠️ *Profil de ${userLabel(user.id)}*\n\nRace : *${user.race || 'Non choisie'}*\nClasse : *${user.className || 'Non choisie'}*\nNiveau : *${user.level}* — ${progress(user)}\nÉnergie : ${bar(user.energy)} ${user.energy}/100\nArme : ${user.weapon} Nv.${user.weaponLevel}\nBerries : ${user.berries.toLocaleString()}\nCola : ${user.cola} | Sea shards : ${user.shards}\nPrime : ${user.bounty.toLocaleString()} B\nVictoires : ${user.wins}/${user.battles}\nHaki : Observation ${user.haki.observation} • Armement ${user.haki.armement} • Conquérant ${user.haki.conquerant}\nFruit : ${user.fruit || 'Aucun'}`; }

ovlcmd({ nom_cmd: 'opmenu', alias: ['onepiece', 'op', 'ophelp'], classe: 'OnePiece', react: '🏴‍☠️', desc: 'Affiche le menu One Piece World Tour.' }, async (_jid, _sock, { repondre }) => reply(repondre, MENU));
ovlcmd({ nom_cmd: 'opguide', alias: ['opregles'], classe: 'OnePiece', react: '📖', desc: 'Explique le fonctionnement du RPG One Piece.' }, async (_jid, _sock, { repondre }) => reply(repondre, `📖 *GUIDE ONE PIECE*\n\n1. Choisis une race et une classe avec *.opchoisir humain pirate*.\n2. Gagne de l’XP avec *.opquete*, *.opcombat* et *.opdaily*.\n3. Utilise tes berries dans *.opshop*.\n4. Améliore ton haki, ton arme et ton bateau.\n5. Avance dans les chapitres, forme ton équipage et bats les boss.\n\nLes données sont sauvegardées localement. Pour une persistance Render durable, configure un volume ou ONEPIECE_DATA_FILE sur un stockage persistant.`));
ovlcmd({ nom_cmd: 'opchoisir', alias: ['opcreate', 'oprace', 'opclasse'], classe: 'OnePiece', react: '🧭', desc: 'Crée ton profil avec une race et une classe.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => {
  const parts = text(arg).toLowerCase().split(/\s+/).filter(Boolean); const user = findUser(jid, auteur_Message);
  if (user.race) return reply(repondre, `✅ Ton profil existe déjà.\n\n${profile(user)}`);
  const race = store.races.find((r) => r.toLowerCase().startsWith(parts[0] || ''));
  const className = store.classes.find((c) => c.toLowerCase().startsWith(parts[1] || ''));
  if (!race || !className) return reply(repondre, `🧭 *Création de profil*\nUtilise : *.opchoisir race classe*\n\nRaces : ${store.races.join(', ')}\nClasses : ${store.classes.join(', ')}`);
  user.race = race; user.className = className; user.energy = 100; user.reputation += 5; saveUser(user, auteur_Message);
  return reply(repondre, `🎉 Bienvenue dans Grand Line, ${userLabel(auteur_Message)} !\nRace : *${race}*\nClasse : *${className}*\n\n${profile(user)}`);
});
ovlcmd({ nom_cmd: 'opprofil', alias: ['opprofile', 'opstats'], classe: 'OnePiece', react: '🪪', desc: 'Affiche ton profil One Piece.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const user = findUser(jid, target(arg, auteur_Message)); return reply(repondre, profile(user)); });
ovlcmd({ nom_cmd: 'opchapitre', alias: ['opchapter', 'opile'], classe: 'OnePiece', react: '🗺️', desc: 'Affiche ou débloque le chapitre suivant.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => {
  const user = findUser(jid, auteur_Message); if (!requireProfile(user, repondre)) return;
  if (lower(arg) === 'next') { if (user.level < user.chapter * 2) return reply(repondre, `🔒 Il te faut le niveau ${user.chapter * 2} pour avancer.`); if (user.chapter >= store.islands.length) return reply(repondre, '🌊 Tu as atteint la dernière île disponible.'); user.chapter += 1; user.island = Math.min(store.islands.length - 1, user.chapter - 1); user.bounty += 250; saveUser(user); return reply(repondre, `🗺️ Nouveau chapitre débloqué : *${user.chapter}* — ${store.islands[user.island]}\nPrime +250 B.`); }
  return reply(repondre, `🗺️ Chapitre *${user.chapter}*\nÎle : *${store.islands[user.island]}*\nCondition suivante : niveau ${user.chapter * 2} et *.opchapitre next*`);
});
ovlcmd({ nom_cmd: 'opquete', alias: ['opquest', 'opmissions'], classe: 'OnePiece', react: '📜', desc: 'Affiche et accomplit une quête quotidienne.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => {
  const user = findUser(jid, auteur_Message); if (!requireProfile(user, repondre)) return;
  if (lower(arg) === 'claim' || lower(arg) === 'faire') { const today = store.today(); if (user.missions[today]) return reply(repondre, '✅ La quête du jour est déjà accomplie.'); user.missions[today] = true; user.berries += 250; user.cola += 1; const result = gain(user, 120); saveUser(user); return reply(repondre, `✅ Quête accomplie ! +250 berries, +1 cola, +${result.gained} XP.`); }
  return reply(repondre, `📜 *Quête du jour*\nVaincre un adversaire ou participer à une activité.\nRécompense : 250 berries, 1 cola, 120 XP.\n\nÉcris *.opquete claim* quand c’est fait.`);
});
ovlcmd({ nom_cmd: 'opmission', alias: ['opmissionsall'], classe: 'OnePiece', react: '🎯', desc: 'Affiche les missions de progression.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); return reply(repondre, `🎯 *MISSIONS DE ${userLabel(auteur_Message)}*\n\n• Atteindre le niveau 5 : ${u.level >= 5 ? '✅' : '⬜'}\n• Gagner un combat : ${u.wins >= 1 ? '✅' : '⬜'}\n• Améliorer le haki : ${Object.values(u.haki).some((v) => v > 0) ? '✅' : '⬜'}\n• Construire un bateau : ${u.boat ? '✅' : '⬜'}\n• Débloquer le chapitre 3 : ${u.chapter >= 3 ? '✅' : '⬜'}`); });
ovlcmd({ nom_cmd: 'opdaily', alias: ['opdailyclaim'], classe: 'OnePiece', react: '🎁', desc: 'Récupère la récompense quotidienne.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); const today = store.today(); if (u.daily === today) return reply(repondre, '⏳ Récompense déjà récupérée aujourd’hui.'); u.daily = today; u.berries += 300 + u.level * 25; u.energy = 100; u.cola += 1; const r = gain(u, 80); saveUser(u); return reply(repondre, `🎁 Daily récupéré ! +${300 + u.level * 25} berries, +1 cola, énergie restaurée, +${r.gained} XP.`); });

async function combat(jid, sock, repondre, auteur_Message, arg) { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; if (u.energy < 10) return reply(repondre, '⚡ Pas assez d’énergie. Utilise *.opdaily* ou attends sa régénération.'); const enemy = lower(arg) || ['bandit', 'marine', 'pirate rival', 'monstre marin'][Math.floor(Math.random() * 4)]; const power = u.level * 20 + u.weaponLevel * 15 + Object.values(u.haki).reduce((a, b) => a + b, 0) * 8 + Math.floor(Math.random() * 60); const difficulty = 35 + u.chapter * 18 + Math.floor(Math.random() * 60); u.energy -= 10; u.battles += 1; if (power >= difficulty) { u.wins += 1; u.berries += 150 + u.level * 20; u.bounty += 100; const r = gain(u, 100 + u.chapter * 20); saveUser(u); return reply(repondre, `⚔️ *VICTOIRE !*\n${userLabel(auteur_Message)} bat *${enemy}*.\nPuissance ${power} contre difficulté ${difficulty}.\n+${150 + u.level * 20} berries • +${r.gained} XP • prime +100 B.`); } saveUser(u); return reply(repondre, `💥 *DÉFAITE*\n*${enemy}* était trop puissant.\nPuissance ${power} contre difficulté ${difficulty}.\nAméliore ton haki, ton arme ou ton niveau.`); }
ovlcmd({ nom_cmd: 'opcombat', alias: ['opbattle', 'opbtl'], classe: 'OnePiece', react: '⚔️', desc: 'Affronte un ennemi ou un membre mentionné.' }, async (jid, sock, { repondre, auteur_Message, arg }) => combat(jid, sock, repondre, auteur_Message, arg));
ovlcmd({ nom_cmd: 'opboss', alias: ['opraid'], classe: 'OnePiece', react: '👹', desc: 'Lance ou attaque un boss de groupe.' }, async (jid, sock, { repondre, auteur_Message, arg }) => { if (!isGroup(jid)) return reply(repondre, '❌ Le boss se joue dans un groupe.'); const g = store.group(jid); const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; if (!g.boss || lower(arg) === 'start') { g.boss = { name: 'Roi des mers', hp: 1000 + u.chapter * 250, maxHp: 1000 + u.chapter * 250, contributors: {} }; store.commit(); return reply(repondre, `👹 *RAID BOSS*\nLe ${g.boss.name} apparaît avec ${g.boss.hp} PV !\nAttaque avec *.opboss hit*.`); } if (lower(arg) !== 'hit') return reply(repondre, `👹 Boss : *${g.boss.name}* — ${g.boss.hp}/${g.boss.maxHp} PV\nÉcris *.opboss hit* pour attaquer.`); const damage = 50 + u.level * 12 + u.weaponLevel * 8; g.boss.hp = Math.max(0, g.boss.hp - damage); g.boss.contributors[auteur_Message] = (g.boss.contributors[auteur_Message] || 0) + damage; if (!g.boss.hp) { u.berries += 800; u.shards += 2; const r = gain(u, 300); saveUser(u); g.boss = null; store.commit(); return reply(repondre, `🏆 *BOSS VAINCU !*\n${userLabel(auteur_Message)} porte le coup final !\n+800 berries • +2 sea shards • +${r.gained} XP.`); } saveUser(u); store.commit(); return reply(repondre, `⚔️ ${userLabel(auteur_Message)} inflige *${damage} dégâts*.\nPV restants : ${g.boss.hp}/${g.boss.maxHp}`); });

ovlcmd({ nom_cmd: 'ophaki', alias: ['optrainhaki'], classe: 'OnePiece', react: '🔥', desc: 'Entraîne un type de haki.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; const type = lower(arg).replace('haki ', '') || 'observation'; const key = Object.keys(u.haki).find((k) => k.startsWith(type.slice(0, 5))); if (!key) return reply(repondre, 'Types : observation, armement, conquerant.'); if (u.berries < 100) return reply(repondre, '💰 Il faut 100 berries pour entraîner ton haki.'); u.berries -= 100; u.haki[key] += 1; const r = gain(u, 60); saveUser(u); return reply(repondre, `🔥 Haki ${key} niveau ${u.haki[key]} ! +${r.gained} XP.`); });
ovlcmd({ nom_cmd: 'optrain', alias: ['opentrainement'], classe: 'OnePiece', react: '🏋️', desc: 'Entraîne ton personnage.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; const r = gain(u, 50); u.energy = Math.max(0, u.energy - 5); saveUser(u); return reply(repondre, `🏋️ Entraînement terminé. +${r.gained} XP, énergie -5.`); });
ovlcmd({ nom_cmd: 'oparme', alias: ['opweapon'], classe: 'OnePiece', react: '🗡️', desc: 'Améliore ton arme.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; const cost = u.weaponLevel * 250; if (u.berries < cost) return reply(repondre, `🗡️ Amélioration : ${cost} berries nécessaires.`); u.berries -= cost; u.weaponLevel += 1; u.weapon = store.weapons[Math.min(store.weapons.length - 1, u.weaponLevel - 1)]; saveUser(u); return reply(repondre, `🗡️ Arme améliorée : *${u.weapon}* niveau ${u.weaponLevel}.`); });
ovlcmd({ nom_cmd: 'opfruit', alias: ['opfruitdemon'], classe: 'OnePiece', react: '🍎', desc: 'Achète ou équipe un fruit mystérieux.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; const choice = store.fruits.find((f) => f.toLowerCase().startsWith(lower(arg))); if (!choice) return reply(repondre, `🍎 Fruits disponibles dans la boutique rare : ${store.fruits.join(', ')}.\nUtilise *.opfruit nom* — coût 2 sea shards.`); if (u.shards < 2) return reply(repondre, '🍎 Il faut 2 sea shards pour obtenir ce fruit.'); u.shards -= 2; u.fruit = choice; saveUser(u); return reply(repondre, `🍎 Tu as obtenu *${choice}* ! Utilise ton pouvoir avec stratégie : le fruit ne remplace pas ton entraînement.`); });
ovlcmd({ nom_cmd: 'opinventaire', alias: ['opinventory', 'opsac'], classe: 'OnePiece', react: '🎒', desc: 'Affiche ton inventaire.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); return reply(repondre, `🎒 *INVENTAIRE*\n\nObjets : ${u.inventory.join(', ') || 'vide'}\nFruit : ${u.fruit || 'aucun'}\nBerries : ${u.berries}\nCola : ${u.cola}\nSea shards : ${u.shards}`); });
ovlcmd({ nom_cmd: 'opshop', alias: ['opboutique'], classe: 'OnePiece', react: '🏪', desc: 'Affiche la boutique One Piece.' }, async (_jid, _sock, { repondre }) => reply(repondre, '🏪 *BOUTIQUE*\n\n1. Potion — 100 berries\n2. Cola — 150 berries\n3. Sea shard — 500 berries\n4. Coffre — 350 berries\n\nAchète avec *.opacheter 1*, *.opacheter 2*, *.opacheter 3* ou *.opacheter 4*.'));
ovlcmd({ nom_cmd: 'opacheter', alias: ['opbuy'], classe: 'OnePiece', react: '🛒', desc: 'Achète un article.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); const item = lower(arg); const offers = { '1': ['Potion', 100], '2': ['Cola', 150], '3': ['Sea shard', 500], '4': ['Coffre', 350] }; const offer = offers[item]; if (!offer) return reply(repondre, 'Choisis un article entre 1 et 4 avec *.opshop*.'); if (u.berries < offer[1]) return reply(repondre, '💰 Pas assez de berries.'); u.berries -= offer[1]; if (item === '2') u.cola += 1; else if (item === '3') u.shards += 1; else u.inventory.push(offer[0]); saveUser(u); return reply(repondre, `✅ Achat effectué : ${offer[0]}.`); });
ovlcmd({ nom_cmd: 'oplootbox', alias: ['opcoffre'], classe: 'OnePiece', react: '🎁', desc: 'Ouvre un coffre de récompenses.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); const index = u.inventory.indexOf('Coffre'); if (index < 0) return reply(repondre, '🎁 Tu n’as aucun Coffre. Achète-en dans *.opshop*.'); u.inventory.splice(index, 1); const rewards = [() => { u.berries += 500; return '+500 berries'; }, () => { u.shards += 1; return '+1 sea shard'; }, () => { u.cola += 3; return '+3 cola'; }, () => { const r = gain(u, 250); return `+${r.gained} XP`; }]; const result = rewards[Math.floor(Math.random() * rewards.length)](); saveUser(u); return reply(repondre, `🎁 Coffre ouvert : *${result}* !`); });

ovlcmd({ nom_cmd: 'opbateau', alias: ['opboat'], classe: 'OnePiece', react: '🚢', desc: 'Construit et consulte ton bateau.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); if (!requireProfile(u, repondre)) return; if (lower(arg) === 'build' || !u.boat) { if (u.boat) return reply(repondre, `🚢 Ton bateau *${u.boat.name}* est niveau ${u.boat.level}.`); if (u.berries < 1000) return reply(repondre, '🚢 Il faut 1 000 berries pour construire ton bateau.'); u.berries -= 1000; u.boat = { name: 'Going OVL', level: 1, expeditions: 0 }; saveUser(u); return reply(repondre, '🚢 Bateau construit : *Going OVL*. Utilise *.opexpedition start*.'); } return reply(repondre, `🚢 Bateau : *${u.boat.name}* niveau ${u.boat.level}\nExpéditions : ${u.boat.expeditions}`); });
ovlcmd({ nom_cmd: 'opexpedition', alias: ['opexp', 'opvoyage'], classe: 'OnePiece', react: '🌊', desc: 'Lance une expédition et récupère une expédition terminée.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); if (!u.boat) return reply(repondre, '🚢 Construis ton bateau avec *.opbateau build*.'); if (lower(arg) === 'collect') { if (!u.expedition) return reply(repondre, 'Aucune expédition en cours.'); if (Date.now() < u.expedition.readyAt) return reply(repondre, `⏳ Expédition encore en cours. Reviens dans ${Math.ceil((u.expedition.readyAt - Date.now()) / 60000)} min.`); u.berries += u.expedition.reward; u.cola += 1; u.expedition = null; saveUser(u); return reply(repondre, '🌊 Expédition récupérée : berries et cola ajoutés.'); } if (u.expedition) return reply(repondre, '⏳ Une expédition est déjà en cours.'); u.expedition = { readyAt: Date.now() + 30 * 60 * 1000, reward: 500 + u.boat.level * 150 }; u.boat.expeditions += 1; saveUser(u); return reply(repondre, '🌊 Expédition lancée. Reviens avec *.opexpedition collect* dans 30 minutes.'); });
ovlcmd({ nom_cmd: 'opequipage', alias: ['opcrew'], classe: 'OnePiece', react: '👥', desc: 'Gère ton équipage et recrute un membre.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const u = findUser(jid, auteur_Message); if (!u.boat) return reply(repondre, '🚢 Construis d’abord ton bateau.'); if (!u.crew) u.crew = []; if (!u.crew.length || lower(arg) === 'recruter') { if (u.berries < 300) return reply(repondre, '👥 Recrutement : 300 berries.'); u.berries -= 300; u.crew.push({ name: ['Roronoa', 'Namiya', 'Usoppu', 'Sanjiro'][u.crew.length % 4], level: 1 }); saveUser(u); return reply(repondre, `👥 Nouveau membre recruté ! Équipage : ${u.crew.map((x) => `${x.name} Nv.${x.level}`).join(', ')}`); } return reply(repondre, `👥 *ÉQUIPAGE*\n${u.crew.map((x, i) => `${i + 1}. ${x.name} — niveau ${x.level}`).join('\n')}`); });
ovlcmd({ nom_cmd: 'opfleet', alias: ['opfaction', 'opflotte'], classe: 'OnePiece', react: '⚓', desc: 'Affiche l’état de ta flotte.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); return reply(repondre, `⚓ Flotte de ${userLabel(auteur_Message)}\nBateau : ${u.boat?.name || 'aucun'}\nÉquipage : ${u.crew?.length || 0} membre(s)\nPrime : ${u.bounty} B`); });
ovlcmd({ nom_cmd: 'oppeche', alias: ['opfish'], classe: 'OnePiece', react: '🎣', desc: 'Pêche une récompense.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); const now = Date.now(); if (u.lastFish && now - u.lastFish < 60 * 60 * 1000) return reply(repondre, '🎣 La mer est calme. Reviens dans une heure.'); u.lastFish = now; const reward = 100 + Math.floor(Math.random() * 250); u.berries += reward; u.cola += Math.random() > 0.7 ? 1 : 0; saveUser(u); return reply(repondre, `🎣 Bonne pêche ! +${reward} berries.`); });
ovlcmd({ nom_cmd: 'opdenden', alias: ['opden-den', 'opcollection'], classe: 'OnePiece', react: '🐌', desc: 'Capture un den den mushi et gagne des shards.' }, async (jid, _sock, { repondre, auteur_Message }) => { const u = findUser(jid, auteur_Message); const now = Date.now(); if (u.lastDenden && now - u.lastDenden < 6 * 60 * 60 * 1000) return reply(repondre, '🐌 Ton den den mushi a besoin de repos.'); u.lastDenden = now; u.shards += 1 + (Math.random() > 0.85 ? 1 : 0); saveUser(u); return reply(repondre, `🐌 Capture réussie ! Tu possèdes maintenant ${u.shards} sea shards.`); });

ovlcmd({ nom_cmd: 'opcolisee', alias: ['opcoliseum', 'oppvp'], classe: 'OnePiece', react: '🏟️', desc: 'Affiche le classement du colisée.' }, async (jid, _sock, { repondre }) => { const users = store.allUsers(jid).sort((a, b) => b.wins - a.wins || b.level - a.level).slice(0, 10); return reply(repondre, `🏟️ *COLISÉE*\n\n${users.length ? users.map((u, i) => `${i + 1}. ${userLabel(u.id)} — ${u.wins} victoire(s), Nv.${u.level}`).join('\n') : 'Aucun combattant.'}`); });
ovlcmd({ nom_cmd: 'opprime', alias: ['opwanted', 'opbounty'], classe: 'OnePiece', react: '🎖️', desc: 'Affiche une prime.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { const id = target(arg, auteur_Message); const u = findUser(jid, id); return reply(repondre, `🎖️ *WANTED*\n\nCible : ${userLabel(id)}\nPrime : *${u.bounty.toLocaleString()} berries*\nRéputation : ${u.reputation}`); });
ovlcmd({ nom_cmd: 'opclassement', alias: ['opleaderboard', 'optop'], classe: 'OnePiece', react: '🏆', desc: 'Affiche le classement One Piece du groupe.' }, async (jid, sock, { repondre }) => { const users = store.allUsers(jid).sort((a, b) => (b.level * 1000 + b.bounty + b.wins * 100) - (a.level * 1000 + a.bounty + a.wins * 100)).slice(0, 10); const mentions = users.map((u) => u.id); const msg = `🏆 *CLASSEMENT ONE PIECE*\n\n${users.length ? users.map((u, i) => `${i + 1}. ${userLabel(u.id)} — Nv.${u.level} • ${u.bounty} B • ${u.wins} victoire(s)`).join('\n') : 'Aucun joueur.'}`; return mentionReply(sock, jid, msg, mentions, repondre); });
ovlcmd({ nom_cmd: 'opreset', alias: ['opabandon'], classe: 'OnePiece', react: '♻️', desc: 'Réinitialise ton profil One Piece.' }, async (jid, _sock, { repondre, auteur_Message, arg }) => { if (lower(arg) !== 'confirmer') return reply(repondre, '⚠️ Cette action efface ton profil. Écris *.opreset confirmer* pour valider.'); const u = findUser(jid, auteur_Message); Object.assign(u, { level: 1, xp: 0, berries: 500, cola: 0, shards: 0, energy: 100, race: null, className: null, weapon: 'Poings', weaponLevel: 1, haki: { observation: 0, armement: 0, conquerant: 0 }, island: 0, chapter: 1, battles: 0, wins: 0, bounty: 0, reputation: 0, crew: null, inventory: ['Potion'], fruit: null, boat: null, expedition: null }); store.update(u); return reply(repondre, '♻️ Ton profil One Piece a été réinitialisé.'); });

module.exports = { MENU };
